name: kashima-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: make install
      - name: Run coverage
        run: make coverage
